"""Initial migration

Revision ID: 03db638524a3
Revises: 
Create Date: 2023-07-22 16:15:09.145555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03db638524a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill')
    # ### end Alembic commands ###
